version: '3.3'

services:
  backend:
    build: backend
    restart: always
    expose:
      - 3000
    networks:
      - internal

  frontend:
    build: frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - internal
  
  database:
    build: database
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - memodb:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  memodb:

networks:
  internal:
